# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-23 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='\u6807\u9898')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='\u6807\u7b7e')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='\u65e5\u671f')),
                ('content', models.TextField(blank=True, null=True, verbose_name='\u5185\u5bb9')),
                ('author_name', models.CharField(max_length=5, verbose_name='\u4f5c\u8005')),
            ],
            options={
                'ordering': ['-date_time'],
                'verbose_name': '\u6587\u7ae0',
                'verbose_name_plural': '\u6587\u7ae0',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('author_category', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': '\u4f5c\u8005',
                'verbose_name_plural': '\u4f5c\u8005',
            },
        ),
    ]
